name: bform
description: Package to allows you to create beautiful forms.
version: 0.1.2
homepage: https://github.com/gabrielgits/bform.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0